name: CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bandit and Safety
        run: |
          pip install bandit safety
      - name: Check requirements file with Safety
        run: |
          safety check -r Installation/requirements.txt
      - name: Check python files for vulnerabilities with Bandit
        run: |
          bandit -r . -ll